### ISSUE TITLE
SpaceVPX connectors

### ISSUE THREAD

**Issue by biedam** [gkasprow/SpaceVPX_FMC_Carrier_3U#11]
Change SpaceVPX connector part numbers from standard to ruggadized. Corresponding P/N in table below:

|   |Standard   |Ruggadized   |  
|---|---|---|
| P0  | 1410189-3  | 2102772-1  |  
|  P1,P2 |1410187-3   | 2102771-1  |  
|  Key Guide |  1-1469492-6 | 2000713-6  |

[Full reference to datasheet](https://www.te.com/commerce/DocumentDelivery/DDEController?Action=showdoc&DocId=Data+Sheet%7F1773466-4_multigig-rt-2-r%7F1212%7Fpdf%7FEnglish%7FENG_DS_1773466-4_multigig-rt-2-r_1212.pdf%7F2000676-8)

**Comment by tprzywoz** [comment]
I created a new component library (copied standard components and changed part number) to prevent an "update from library" issue.
