### ISSUE TITLE
Mechanical issues

### ISSUE THREAD

**Issue by mkuklewski** [gkasprow/SpaceVPX_FMC_Carrier_3U#16]
1. 8 holes on PCB sides, should be fi 2,2mm (for M2 screws) - right now some of them are smaller
2. The minimum distance from the side edges of Carrier PCBs to the nearest component or pad should be 12.5 mm. - This will ensure proper case placement
3. The minimum distance from the side with SpaceVPX connector to the nearest component or pad should be 14.5mm. Although here it is not required - only nice to have. We have decided to make a 1-2mm cut-out in the case on this side.

![obraz](https://user-images.githubusercontent.com/47330304/65241896-08b5aa00-dae5-11e9-856f-1b0ddc7f0b05.png)

[SVPX_3U_080_PCB_obrys_bazowy_20190828.PDF](https://github.com/elhep/SpaceVPX_FMC_Carrier_3U/files/3631064/SVPX_3U_080_PCB_obrys_bazowy_20190828.PDF)

**Comment by tprzywoz** [comment]
1. fixed
2. done with exception: J1 J3. There is no way to fit them.
3. I left this one.  It would require a lot of work with replacement, so if it's not necessary...
