### ISSUE TITLE
SpaceVPX connector pinout change.

### ISSUE THREAD

**Issue by mkuklewski** [gkasprow/SpaceVPX_FMC_Carrier_3U#2]
During further development of the project and review,  the need to change the pinout became apparent.
First all connectors should be grouped to different sheets and named after each connector (and those placed into one, from which all harness should spread) and all pins should be named after standard.

Naming of each sheet should be like this:
SLT3-PAY-1Q2T-HS_COMM 
SLT3-PAY-1Q2T-HS_COMM_P0
SLT3-PAY-1Q2T-HS_COMM_P1 
etc.

Pinout of the SpaceVPX connector is here:
https://docs.google.com/spreadsheets/d/13T0c5s93cGWtUubSEh7cbfTNiu5ucbjdAXt16fslpvk/edit?usp=sharing

**Comment by tprzywoz** [comment]
Done. In MSP430_power_jtag sheet I added TVS diode to MCU_UART.
