### ISSUE TITLE
FPGA Supply - Capacitors and resistors

### ISSUE THREAD

**Issue by mkuklewski** [gkasprow/SpaceVPX_FMC_Carrier_3U#6]
According to Microsemi_SmartFusion2_IGLOO2_Board_and_Layout_Design_Guidelines_Application_Note_AC393_V13.pdf there is not enough decoupling capacitors. 
For XXXX should be:
- VDDI1 - 7 x 0.01 μF,  7 x 0.1 μF, 2 x 47 μF
- VDDI2 - 2 x 0.01 μF,  2 x 0.1 μF, 1 x 10 μF
- VDDI3 - 2 x 0.01 μF,  2 x 0.1 μF, 1 x 10 μF
- VDDI4 - 1 x 0.01 μF, 1 x 10 μF
- VDDI5 - please add to those which already are 2 x 0.01 μF,  2 x 0.1 μF
- VDDI6 - please add to those which already are 2 x 0.01 μF,  2 x 0.1 μF
- VDDI7 - please add to those which already are 2 x 0.01 μF,  2 x 0.1 μF
- VDDI8 - please add to those which already are 2 x 0.01 μF,  2 x 0.1 μF
- VDD - 10 x 0.01 μF, 10 x 0.1 μF, 1 x 100 μF, 3 x 220 μF, 1 x 330 μF
- VPP - 2 x 0.01 μF,  1 x 0.1 μF, 1 x 10 μF
- VREF - we are using it  - each resistor should be 1k Ohm. Capacitors which should be here: 2 x 0.01 μF,  1 x 0.1 μF, 1 x 10 μF
- VPPNVM - not enough capacitors - 1 x 0.01 μF,  1 x 10 μF
- SERDES_0_L01_VDDAIO - is connected to SERDES_0_VDD - Voltage is ok, but there is not enough capacitors
-- SERDES_0_VDD - should be 1 x 0.01 μF,  1 x 0.1 μF, 1 x 10 μF
-- SERDES_0_L01_VDDAIO - should be 1 x 0.01 μF,  1 x 0.1 μF, 1 x 10 μF
- SERDES_0_L23_VDDAIO - should be one 100nF capacitor less

**Comment by tprzywoz** [comment]
I added the missing capacitors and replaced resistors. I didn't reduce quantity of capacitors if the capacity was greater than required.
