### ISSUE TITLE
FPGA Config

### ISSUE THREAD

**Issue by mkuklewski** [gkasprow/SpaceVPX_FMC_Carrier_3U#7]
FLASH_GOLDEN_N and DEVRST_N are pulled up by 1kOhm - should be 10 kOhm resistor.
JTAG voltage is connected to 2V5 - should be 3V3 - also it would be probably wise to add transil diodes.

**Comment by tprzywoz** [comment]
done

**Comment by tprzywoz** [comment]
Added new FPGA reset schematics:
![image](https://user-images.githubusercontent.com/30114557/56093265-77ebfa00-5ec6-11e9-8e4c-1d8f6259221d.png)
