### ISSUE TITLE
JTAG connector

### ISSUE THREAD

**Issue by biedam** [gkasprow/SpaceVPX_FMC_Carrier_3U#9]
Use 2mm pitch socket which is already in schematic. If it doesn't fit then try with THT version: (https://katalog.we-online.de/en/em/BHD_2_00_MALE_BOX_HEADER_6250XX21621). It it's still to large, then use vertical Pico-Blade female connector from Molex.

MSP430 JTAG connector is already used in different PCB so it should stay the same as in schematic.

**Comment by tprzywoz** [comment]
Used THT version: WR-BHD 2.00 mm Male Box Header 62501021621
